---
- hosts: webserver
  become: true
  tasks:
  - name: Install Apache httpd
    yum: name=httpd state=present
  - name: Copy the index.html file web dir
    copy: index.html /var/www/html/index.html
  - name: Start httpd
    service: name=httpd state=started enabled=yes
