- name: create ec2 instances
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    hostlist: []
  tasks:

    - name: provision instances
      ec2:
        key_name: Mac
        group: launch-wizard-4
        region: us-east-1
        instance_type: t2.micro
        image: ami-04681a1dbd79675a5
        exact_count: 3
        count_tag:
          Name: autospin
        instance_tags:
          Name: autospin
      register: ec2
    - name: wait for instances
      pause:
        minutes: 1

    - name: create hostlist
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.tagged_instances }}"
    # - debug:
    #     var: ec2

- name: install
  hosts: launched
  become: True
  tasks:
    - name: install apache
      yum:
        name: httpd
        state: present

        