- name: create ec2 instances
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

    - name: provision instances
      ec2:
        key_name: devbox
        group: launch-wizard-4
        region: us-east-1
        instance_type: t2.micro
        image: ami-04681a1dbd79675a5
        exact_count: 3
        count_tag:
          Name: autospin
        instance_tags:
          Name: autospin
      register: ec2

    - name: Wait for SSH to come up
      delegate_to: "{{ item.private_dns_name }}"
      wait_for_connection:
        delay: 60
        timeout: 320
      with_items: "{{ ec2.instances }}"
    - ec2_instance_facts:
        region: us-east-1
        filters:
          instance-state-name: running
          "tag:Name": autospin
      register: ec2facts
    - debug:
        var: ec2facts
    - name: create hostlist
      add_host:
        hostname: "{{ item.private_dns_name }}"
        groupname: launched
      with_items: "{{ ec2facts.instances }}"
    
    # - debug:
    #     msg: "{{ item }}"
    #   with_inventory_hostnames:
    #     - all: launched

- name: install
  hosts: launched
  become: True
  tasks:
    - name: install
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - httpd
        - mlocate
        - strace
    

        