- name: terminate
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - ec2_instance_facts:
        region: us-east-1
        filters:
          "tag:Name": autospin
      register: ec2
    - debug:
        msg: "{{ (ec2.stdout | from_json).instances.instance_id }}"
        
    - ec2:
        state: 'absent'
        instance_ids: '{{ ec2.instance_id }}'
      with_items: ec2
