- name: terminate
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - local_action:
      module: ec2
        region: us-east-1
        instance_tags:
          Name: autospin
      state: stopped
