- name: terminate
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - ec2_instance_facts:
        region: us-east-1
        filters:
          "tag:Name": autospin
      register: result
    - debug:
        var: result[instance_id]
    # - local_action:
    #     module: ec2
    #     region: us-east-1
    #     instance_tags:
    #       Name: autospin
    #     state: stopped
    

