- name: terminate
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - ec2_instance_facts:
        region: us-east-1
        filters:
          "tag:Name": autospin
      register: ec2
    - debug:
        msg: "Id is {{ ec2.instance_id }}"
    # - ec2:
    #     state: 'absent'
    #     instance_ids: '{{ ec2.instance_ids }}'
