- name: terminate
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - ec2_instance_facts:
        region: us-east-1
        filters:
          "tag:Name": autospin
      register: ec2
    # - debug:
    #     var: ec2
        
    - ec2:
        state: 'absent'
        instance_ids: '{{ ec2.instance_id[0].id }}'
      with_items: ec2
