---
- hosts: all
  gather_facts: true
  remote_user: vagrant
  tasks:
   - name: Run some random commands
     command: hostname -f
   - name: test the connection
     ping:
     remote_user: vagrant
  
   - yum: pkg=httpd state=installed

- hosts: webserver
  gather_facts: true
  remote_user: vagrant
  tasks:
   - name: test the connection
     ping:
     remote_user: vagrant
    
   - yum: pkg=httpd state=installed
