---
- hosts: webserver
  tasks:
  - name: Stop and remove nginx
    service: name=nginx state=stopped
  - name: Remove nginx package
    yum: name=nginx state=removed
  ignore_errors: yes

- hosts: webserver
  tasks:
    # Example that prints the loopback address and gateway for each host
    - debug:
        msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"

    - debug:
        msg: "System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}"
      when: ansible_default_ipv4.gateway is defined

    - shell: /usr/bin/uptime
      register: result

    - debug:
        var: result
        verbosity: 2

    - name: Display all variables/facts known for a host
      debug:
        var: hostvars[inventory_hostname]
        verbosity: 4

- hosts: webserver
  become: true

  vars_files:
    - "vars.yml"

  roles:
    - ntp
    - httpd
    - deploy_static_content